/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RegisterInfoCard: typeof import('./components/RegisterInfoCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
