/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/changelog': RouteRecordInfo<'/changelog', '/changelog', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/contact': RouteRecordInfo<'/dashboard/contact', '/dashboard/contact', Record<never, never>, Record<never, never>>,
    '/dashboard/gegevens': RouteRecordInfo<'/dashboard/gegevens', '/dashboard/gegevens', Record<never, never>, Record<never, never>>,
    '/dashboard/ledenlijst': RouteRecordInfo<'/dashboard/ledenlijst', '/dashboard/ledenlijst', Record<never, never>, Record<never, never>>,
    '/dashboard/tickets': RouteRecordInfo<'/dashboard/tickets', '/dashboard/tickets', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/placeholder': RouteRecordInfo<'/placeholder', '/placeholder', Record<never, never>, Record<never, never>>,
  }
}
